sudo: required
dist: trusty
language: python
python:
  - "3.6"
  - "3.7-dev"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
install:
  - pip install -U --pre pip setuptools
  - pip install -r requirements/ci.txt
  - pip list --format=columns
before_script:
  - echo
script:
  - tox -e
after_success:
  - coveralls

notifications:
  email: never
